name: flutter_baidutts
description: flutter plugin for baidu tts
version: 0.0.6
authors:
  - 296683519@qq.com
homepage: https://github.com/lyqiai/flutterBaiduTts
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: river.com.flutter_baidutts
        pluginClass: FlutterBaiduttsPlugin
      ios:
        pluginClass: FlutterBaiduttsPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
